name: Output Event Details
on: issues
jobs:
  info:
    runs-on: ubuntu-latest
    name: output details
    steps:
      - name: Output Github context
        run: echo "${{ toJSON(github.event) }}" # Output github data. 
