name: testing
on: push
jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: lint
        run: echo "Linting..."
      - name: Run lint
        run: npm run lint
  test:
    name: Run Test
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: test
        run: echo "Testing..."
      - name: Run tests
        run: npm run test
      - name: test
        run: echo "Testing..."
  deploy:
    name: Build Project
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."
